---
- hosts: appservers
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Install wget
      apt:
        name: wget
        state: present

    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.82/bin/apache-tomcat-9.0.82.tar.gz
        dest: /opt/apache-tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Start Tomcat
      command: nohup /opt/apache-tomcat-9.0.82/bin/startup.sh
