---
- hosts: appservers
  become: yes
  vars:
    tomcat_version: 9.0.82
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Install wget
      apt:
        name: wget
        state: present

    - name: Download Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /opt/apache-tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Start Tomcat
      command: nohup /opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
